### ISSUE TITLE
get error when generating data.

### ISSUE THREAD

**Issue by nnzhan** [liyaguang/DCRNN#15]
Could you please help me fix the error. When I run 
```
python -m scripts.generate_training_data --output_dir=data/METR-LA
```
I get the following logs
```
Traceback (most recent call last):
  File "/home/zhwu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/zhwu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zhwu/workspace/DCRNN/scripts/generate_training_data.py", line 123, in <module>
    main(args)
  File "/home/zhwu/workspace/DCRNN/scripts/generate_training_data.py", line 108, in main
    generate_train_val_test(args)
  File "/home/zhwu/workspace/DCRNN/scripts/generate_training_data.py", line 85, in generate_train_val_test
    x_train, y_train = x[:num_train], y[:num_train]
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by zwd2016** [comment]
I think this is a problem caused by the division syntax of the Python 2.7 version. You can run this code in Python 3.5.

**Comment by nnzhan** [comment]
thanks, it solves my problem

**Comment by liyaguang** [comment]
Thanks @zwd2016 . Glad it solves the problem.

**Comment by Lorrainexun** [comment]
Hi, can you help me with this error.   I have run `python -m scripts.generate_training_data --output_dir=data/METR-LA` in Python 3.7.2, but I got the error:

`C:\Users\mlvis\AppData\Local\Programs\Python\Python37-32\python.exe: Error while finding module specification for 'scripts.generate_training_data' (ModuleNotFoundError: No module named 'scripts')`

**Comment by Lorrainexun** [comment]
Hi can you help me with this error. When generating data, I got the following logs:

> C:\Users\mlvis\Documents\Emma\DCRNN>python -m scripts.generate_training_data --output_dir=data/METR-LA --traffic_df_filename=data/metr-la.h5
Generating training data
Traceback (most recent call last):
  File "C:\Users\mlvis\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\mlvis\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mlvis\Documents\Emma\DCRNN\scripts\generate_training_data.py", line 123, in <module>
    main(args)
  File "C:\Users\mlvis\Documents\Emma\DCRNN\scripts\generate_training_data.py", line 108, in main
    generate_train_val_test(args)
  File "C:\Users\mlvis\Documents\Emma\DCRNN\scripts\generate_training_data.py", line 72, in generate_train_val_test
    add_day_in_week=False,
  File "C:\Users\mlvis\Documents\Emma\DCRNN\scripts\generate_training_data.py", line 47, in generate_graph_seq2seq_io_data
    x_t = data[t + x_offsets, ...]
MemoryError
