### ISSUE TITLE
Got an error install on MacOS

### ISSUE THREAD

**Issue by rmcarthur** [liyaguang/DCRNN#20]
Just wanted to let you know I got this error due to tables not being installed, while generating training data.

```
Generating training data
Traceback (most recent call last):
  File "/Users/rex/anaconda3/envs/traffic/lib/python3.7/site-packages/pandas/io/pytables.py", line 466, in __init__
    import tables  # noqa
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rex/anaconda3/envs/traffic/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/rex/anaconda3/envs/traffic/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/rex/Work/DCRNN/scripts/generate_training_data.py", line 123, in <module>
    main(args)
  File "/Users/rex/Work/DCRNN/scripts/generate_training_data.py", line 108, in main
    generate_train_val_test(args)
  File "/Users/rex/Work/DCRNN/scripts/generate_training_data.py", line 57, in generate_train_val_test
    df = pd.read_hdf(args.traffic_df_filename)
  File "/Users/rex/anaconda3/envs/traffic/lib/python3.7/site-packages/pandas/io/pytables.py", line 368, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, **kwargs)
  File "/Users/rex/anaconda3/envs/traffic/lib/python3.7/site-packages/pandas/io/pytables.py", line 469, in __init__
    'importing'.format(ex=ex))
ImportError: HDFStore requires PyTables, "No module named 'tables'" problem importing
```

 It should be added to requirements.txt, but it doesn't install correctly right off the bat. I needed an HDF5 install as well, which is brew installable. Inside a venv, I ended up doing the following:

```
brew install hdf5
source activate my_venv
pip install tables
```

But that gave me terrible errors as well, that I can't get around. 
```
$ pip install tables
Collecting tables
    /var/folders/wp/n612s6296jzf_yspjjs1ys1m0000gn/T/H5close6qg7st18.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
    main (int argc, char **argv) {
    ^
    /var/folders/wp/n612s6296jzf_yspjjs1ys1m0000gn/T/H5close6qg7st18.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]
        H5close();
        ^
    2 warnings generated.
    * Using Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 10:30:07)
    * USE_PKGCONFIG: False
    * Found conda env: ``/Users/rex/anaconda3/envs/traffic``
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wp/n612s6296jzf_yspjjs1ys1m0000gn/T/pip-install-273jy0so/tables/
```
I have hdf5 installed, and I use it locally all the time. I tried to pass it as described there, but to no avail. 

It does work outside of my venv for now, so I'll do that. But if anyone gets this running inside a condo venv on MacOs, please let me know.

**Comment by zowieappreciationnow** [comment]
I cannot reproduce this. I'm on 10.14, using homebrew's python==3.7.2 and hdf5==1.10.4.

I guess the reason is that you are using **python from anaconda** but **hdf5 from homebrew**.

Can you try "conda install -c anaconda hdf5 " and re-run "pip install tables"?
