### ISSUE TITLE
run_demo.py not working on PEMS-BAY data

### ISSUE THREAD

**Issue by Lorrainexun** [liyaguang/DCRNN#26]
Hi, Can you help me with this error? I have run 

> python run_demo.py --config_filename=data/model/pretrained/PEMS-BAY/config.yaml --output_filename=data/results/dcrnn_bay_predictions.npz

and the error log is listed as follows:

> Unable to load data  data/sensor_graph/adj_mx_bay.pkl : the STRING opcode argument must be quoted
Traceback (most recent call last):
  File "run_demo.py", line 37, in <module>
    run_dcrnn(args)
  File "run_demo.py", line 20, in run_dcrnn
    _, _, adj_mx = load_graph_data(graph_pkl_filename)
  File "C:\Users\mlvis\Documents\Emma\DCRNN\lib\utils.py", line 198, in load_graph_data
    sensor_ids, sensor_id_to_ind, adj_mx = load_pickle(pkl_filename)
  File "C:\Users\mlvis\Documents\Emma\DCRNN\lib\utils.py", line 205, in load_pickle
    pickle_data = pickle.load(f)
_pickle.UnpicklingError: the STRING opcode argument must be quoted

Thanks a lot for your help!

**Comment by liyaguang** [comment]
This seems to be the problem of `unpickling`, have you tries to load the file with `Python3`?
